### ISSUE TITLE
RemoteApp Tool 5.3.0.0

### ISSUE THREAD

**Issue by sashaqwert** [kimmknight/remoteapptool#124]
Previously video in README repository RemoteApp Tool 5.3.0.0.
Now I don't see it.
I found this version: [RemoteApp Tool 5300.zip](https://github.com/user-attachments/files/16511615/RemoteApp.Tool.5300.zip)

**Comment by kimmknight** [comment]
Glad you found it. Are you suggesting we add a link to it from the README?

**Comment by kimmknight** [comment]
I have updated the README with links to older releases. Link added to the Releases page, and link also added to the wiki page that contains info and download links for the *really* old releases.
