### ISSUE TITLE
Print from local printer

### ISSUE THREAD

**Issue by juanarelmor** [kimmknight/remoteapptool#125]
The app works great, except that I need to print from local printers.

How do I print from my local printers?

Thank you very much

**Comment by kimmknight** [comment]
Just tested this. For me it just worked. All my local printers are all available from within any RemoteApp.

The printers have the same name that they have on my local client PC, but with _(redirected n)_ on the end. For example:

_Brother HL-1110 (redirected 2)_

In addition to the local (client) printers, also listed were the local printers on the host PC.

Unsure what your issue might be sorry.
