### ISSUE TITLE
RemoteApp Tool fails to launch if Remote Desktop Connection is not installed

### ISSUE THREAD

**Issue by aaronparker** [kimmknight/remoteapptool#128]
Remote Desktop Connection can be uninstalled on Windows 11 23H2. RemoteApp Tool fails to launch if Remote Desktop Connection is not installed - no error is shown, the executable launches and looks for `C:\Windows\System32\mstsc.exe` and then exits.

Fairly obvious that Remote Desktop Connection needs to be installed, but perhaps the RemoteApp Tool may need to run a check that RDC is installed and display a message if it isn't.

[Uninstall and reinstall Remote Desktop Connection](https://learn.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/uninstall-remote-desktop-connection)

To replicate the issue:

* On the server-side (Windows 11 or Windows Server 2025), uninstall Remote Desktop Connection
* Start RemoteApp Tool - if no RemoteApps are defined the tool will launch
* Create a RemoteApp - the tool will exit after creating the app
* Attempt to relaunch the RemoteApp Tool - the executable will start and look for `C:\Windows\System32\mstsc.exe` (determined via Process Monitor), fail to display the application and exit without errors or other messages

**Comment by aaronparker** [comment]
This issue is on the server-side, not the client. I realise it's not a bug with the tool, I'm suggesting the tool checks for mstsc.exe and tell the user to re-install the tool if it's been uninstalled on the server. Otherwise the tool never launches.

**Comment by MrBrianGale** [comment]
I was unaware that mstsc was required to make a connection TO the server. I was under the impression that was a client side tool.
But best practices with server administration is that you don't use the server "physically" unless that is the ONLY option. Windows Servers (even those running desktop OS's which is a bad idea to begin with) shouldn't have people physically at the machine. The machine should be secured.
That being said, I'm still not certain what the point of RemoteApps is on a single-user machine (ie desktop OS). Is there really a benefit to using remote apps on Windows 11?

But I am getting off topic. I'll re-open this and, time permitting, it can be added.

**Comment by aaronparker** [comment]
I should have added more details on the issue - I've updated the first comment

**Comment by aaronparker** [comment]
@kimmknight yeah, it's pretty amusing revisiting this after all these years. :)

**Comment by kimmknight** [comment]
Found it!

![image](https://github.com/user-attachments/assets/2577dcdc-a42a-489c-a5dd-1f69363bcced)

**Comment by kimmknight** [comment]
Fixed with commit ab3ae88
