### ISSUE TITLE
Add Programs To RD Web?

### ISSUE THREAD

**Issue by Arefu** [kimmknight/remoteapptool#13]
This might not be the tools fault, it might be because I am using server 2019, but how can I add the apps to the RD Web? I've checked the box in the tool, but they don't appear and I can't see any groups in Local users & groups that will give access?

**Comment by thirdwheel** [comment]
Did you put the rdp files where RAWeb can see them?

**Comment by thirdwheel** [comment]
If you're using Windows' RemoteApp, you don't need this tool, you should use RemoteApp Manager, which comes with Windows once the correct role is installed.

**Comment by Arefu** [comment]
Wait, you need to put them in a folder lol?

I thought this would behave like the normal app manager sorry, where do I need to put them?
Also, that would be fine but apparently that requires a domain, I am not on a domain

**Comment by bmg002** [comment]
If you are using the RA WEB tool developed by Kimmknight, follow the directions in the readme for that.
If you are using Windows Server 2019's RD Web, then you need to use the server manager tool.
As you are using Server 2019, I would recommend, to use the built in server Manager.  I am pretty sure you do not need the computer to be domain joined.  You just need to add all of the appropriate roles to the server. 

If you want to use the RemoteAppTool, I strongly encourage you to use the RA WEB tool also developed by Kimmknight.

**Comment by Arefu** [comment]
Yeah, you do need to be domain joined since you need to be logged in as admin, it's OK I ended up doing that getting the reg keys I needed then removed AD.

Yeah I also found that but had some issues with UWP RDP accepting it as a web feed.

**Comment by bmg002** [comment]
I know I am replying to a closed issue, but I think you are mistaken there.  You can log in as an admin without a device being domain joined.  The "administrator" account is a local account, not a domain account usually.  Domain Admin is a group on a domain who has admin on all machines.  You can even add a user to the admin group.

**Comment by Arefu** [comment]
Then I wasn't clear in what I said.

When you try open the RD Web area on a Session Broker it alerted me I can't configure anything as a local admin and I need to sign into a domain administrator account and try again.
