### ISSUE TITLE
Add feature to accept drag and drop for creating new applications

### ISSUE THREAD

**Issue by systemmonkey42** [kimmknight/remoteapptool#131]
Hi, I've just discovered your tool, and I have a couple of ideas..

It would be handy to accept drag and drop of an exe file on the main application window
to create one or more applications.

It would also be nice if I could select all (ctrl-a) or some (ctrl-click) programs and bulk export the RDP files.

Support for URL's.  I have a number of RDP files which contain:
```
remoteapplicationprogram:s:https://mail.google.com/
```
(amongst other settings) for example simply to launch the default browser with the provided url.

I currently have over 700 RDP files to launch different apps on different computers, some are URL's which I'm not even sure how to reproduce with your tool.   Drag-and-drop, and bulk export would make conversion simple and convenient.

Thanks

**Comment by MrBrianGale** [comment]
Drag and drop could probably work but you'd miss all the extra config steps so I'd advise against it. As for multistory, that sounds like a nice featureBut not sure on the timeline to implement. 
I am a bit curious why you'd want to open a webpage through an rdp session though? You lose hardware acceleration by doing that and all computers have web browser already. What is the benefit?

**Comment by systemmonkey42** [comment]
Thanks for the response.

> Drag and drop could probably work but you'd miss all the extra config steps so I'd advise against it.

It would be the same as hitting the '+' icon, which seems to work perfectly.  I'm fairly new to this so I'm not sure what extra steps occur unless you are using the "New RemoteApp (Advanced)..." option

> I am a bit curious why you'd want to open a webpage through an rdp session though?

Context and security.  The web page is usually for a login portal which is local to the site I'm RDPing to, or effectively inaccessible from my local desktop. 
Sometimes its a URL on the default browser, sometimes its a specific browser with a specific profile
```
remoteapplicationprogram:s:C:\Program Files\Google\Chrome\Application\chrome.exe
remoteapplicationcmdline:s:--profile-directory="exo_profile" --allow-no-sandbox-job --disable-gpu
```

I've been using remote desktop this way since on windows 7 since 2012, but I've always built the commands and settings into the RDP file and disabled the "AllowList" on the remote host. You applications ability to configure the remote host correctly without dropping all security is a plus.

also also...
It struck me that dropping a shortcut or existing RDP file on the app should also work..
- extract the program name, command line, arguments, working directory and icon then create a new application with those settings

Clearly I'm fishing for a way to migrate my existing collection of rdp files with minimum effort....

**Comment by MrBrianGale** [comment]
So was just reading that and you are starting chrome with arguments over rdp, not loading a webpage directly. I do still find this odd behavior but makes more sense to me now. 
As for extracting the information through drag and drop, I'm not certain all of that information is available from the API. Arguments definitely would not be, and icon might not be either... I believe the drag and drop has one of two behaviors: either it provides the object where it is possible to extract the path and file name and such or it provides a copy of the object in which case the path may be harder to extract...

I'm also not understanding how this would help with the 700 rdp files you currently have. This tool isn't for managing your rdp files, it is for creating the setup for remote apps without the need of the Microsoft front end. It will create the rdp files for distribution but it isn't an rdp management tool...

**Comment by kimmknight** [comment]
Some cool ideas, thanks @systemmonkey42 !

**Comment by systemmonkey42** [comment]
As a test, I wrote a script which I used to convert 200 "verbose" rdp files into a pair of REG and minimal RDP files.

Once I loaded the reg file, it all mostly worked
- [x] Applications appear in the registry
- [x] Applications appear in RemoteAppTool
- [x] Applications which configure "path"="c:\....\application.lnk" work.
- [x] Applications with command line parameters work.
- [x] Application which configure "path"="http://<some url goes here>/" works.
- [x] Edit and Re-export RDP files from RemoteAppTool for all apps which point directly to an "EXE" or "MSC" file.
- [ ] Edit applications which refer to LNK files in RemoteApp (causes attached crashdump)
- [ ] Edit applications which refer to URLs in RemoteApp (also crashes)

With 200 applications, RemoteAppTool became fairly slow...

As an aside, If I try and add a "shortcut" as an application, RemoteAppTool unpacks the EXE and PATH from the shortcut, and discards the shortcut.  This is actually a bad idea.  Just add the shortcut.
Application Compatibility settings and the "run as administator" flags are part of the shortcut, not the exe, or the RDP configuration.

The only way to launch an elevated command prompt or powershell for example, is to create a shortcut to CMD.exe, configure it to run as administrator, and have remote desktop launch the shortcut.

This demonstrably works, however isn't supported by your application.

Regards

[crashdump.txt](https://github.com/user-attachments/files/17054281/crashdump.txt)

**Comment by kimmknight** [comment]
@systemmonkey42 - your use of RemoteApp Tool is unconventional and interesting. The features you are requesting are not a priority for most users of the tool. While I'm unlikely to have time to investigate/implement these anytime soon myself, I'm keen to add your suggestions as individual issues in the repo.

I think I have boiled it down to a handful of issues/feature requests:

### Drag and Drop Support:

- Allow dragging and dropping of .exe files (and possibly .lnk files) to create applications.

### Bulk Export Functionality:

- Implement a feature to select multiple applications (using Ctrl+A or Ctrl-click) for bulk exporting of RDP files.

### URL Support:

- Allow creating, editing, and exporting of RDP files for applications that refer to URLs (without crashing).

### Shortcut Support:

- When adding a RemoteApp and a shortcut is selected (instead of an exe), allow the option to preserve the shortcut path instead of resolving it to the exe.
- Allow creating, editing, and exporting of RDP files for applications that refer to .lnk files (without crashing).

### Performance Improvements:

- Address performance issues when managing a large number of applications (e.g., over 200 RemoteApps).

**Comment by systemmonkey42** [comment]
> Do you think this is a reasonable summary?
Perfectly.

I'm keen to stop hand massaging hundreds of RDP files (which I occasionally have to clone and bulk edit to change host names or drive paths).  These few additional features would make it trivial.

Thanks for your time.

**Comment by kimmknight** [comment]
I have split this into individual issues/feature requests #132, #133, #134, #135, and #136.

Just to set a realistic expectation @systemmonkey42 , it is unlikely these will be implemented anytime soon.

I will now close this issue.
