### ISSUE TITLE
Fail to launch any app.

### ISSUE THREAD

**Issue by BlackBatM4n** [kimmknight/remoteapptool#138]
hi,
I'm using a windows 7 pro, I tried to test your tool with paint and vscode, but it fails to launch.
When I launch the RDP connection, it asks for login, as soon as I enter my credential it closes, the login is correct.

the only log i have is this:
 `Driver exit RTD3.
 All the connected devices will now cause DeviceConnected events.`

By the way nice project, if it works it will save my life.

**Comment by kimmknight** [comment]
This issues is that Win 7 Pro doesn't support RemoteApps 😞

See the [compatibility chart](https://github.com/kimmknight/remoteapptool/wiki/Windows-Compatibility).

_If you try to host RemoteApps on an incompatible edition of Windows (eg. Windows 10 Home), the tool will run but RemoteApps will not work. The RDP client will appear to be connecting, then just disappear with no error shown._

Sorry for the bad news.
