### ISSUE TITLE
Works in Windows 10 Pro?

### ISSUE THREAD

**Issue by thirdwheel** [kimmknight/remoteapptool#14]
Hi

Not an issue, just letting you know that it seems to work in Win 10 Pro.

![image](https://user-images.githubusercontent.com/160601/76809423-e526ae80-683e-11ea-96b8-1d0256b7fe89.png)

**Comment by psyhlo** [comment]
[https://github.com/kimmknight/remoteapptool/wiki/Windows-Compatibility](url)

**Comment by kimmknight** [comment]
Thanks thirdwheel, I'm guessing you are referring to the misleading compatibility chart on kimknight.net/remoteapptool. As psyhlo mentioned, the compatibility page on the wiki here should be more accurate. I'll fix/replace the website sometime :-)
