### ISSUE TITLE
How to save credentials (login and password) ?

### ISSUE THREAD

**Issue by Vaki-86** [kimmknight/remoteapptool#147]
Hello everyone! I found the option to save login (username). Is there a way to save the password as well? The goal is to automate the launch of a remote application (without having to enter login and password each time).
![screen](https://github.com/user-attachments/assets/27c4956a-2561-41db-b481-6ba4442e9089)

**Comment by kimmknight** [comment]
Normally you would just authenticate once (with default Network Level Authentication) and click the "Remember me" checkbox. The credentials will be stored in the Credential Manager on the client device.

If for some reason you must store the credentials in the RDP file, you could try this:

There is an RDP file option called "password 51" that can be specified in RDP files which stores "The user password in a binary hash value.".

You could use [rdp-file-password-encryptor](https://github.com/RedAndBlueEraser/rdp-file-password-encryptor) to encrypt your password and save it in there (along with a username).

I have tested and this works, however, the encrypted password is specific to the user and machine that it was generated on, so if you copy the RDP file to another computer, it can not use the stored password and will prompt.

**Comment by kimmknight** [comment]
Basically, Microsoft don't want you storing passwords in RDP files. The workaround mentioned above may or may not work. Either way, not an issue with RemoteApp Tool, so I'll close this issue.

Post in Discussions if you want to discuss further.

**Comment by wowpala** [comment]
Find your .rdp file, add the following lines:

```
enablecredsspsupport:i:1
authentication level:i:2
prompt for credentials:i:0
```
