### ISSUE TITLE
Russian characters and underscores in Server Name field creating problems

### ISSUE THREAD

**Issue by kimmknight** [kimmknight/remoteapptool#2]
https://groups.google.com/d/msg/remoteapptool/yGUhwqBzbT4/HuS_7vR7DAAJ

**Comment by kimmknight** [comment]
Great, thanks for looking into the issue! I have merged the commit for issue #1 - thanks for that, but I can't see any changes anywhere relating to this issue #2. I am fairly new to GitHub - am I missing something?

**Comment by bmg002** [comment]
I didn't want to create the pull request for issue #2 fix unless issue #1 fix was merged as I accidentally merged the code on my end.  So if Issue #1 fix was denied to be merged, but issue  #2 fix was merged, then both would have been merged.
This was just bad practice on my part.  I should have done the branching differently.

**Comment by kimmknight** [comment]
bmg002 updated the RegEx pattern and this issue should now be resolved. Thanks bmg002!
