### ISSUE TITLE
printer redirection

### ISSUE THREAD

**Issue by romansuda** [kimmknight/remoteapptool#20]
Hi,
it looks like some of printers are not redirected while using app via remoteapp (tested on w10 enterprise).
The same printers are redirected while using regulary connection via RDP

Does anybody know, where is the problem hidden?

thanks

**Comment by romansuda** [comment]
solved by installing drivers via printmanagement.msc

**Comment by Neustradamus** [comment]
@romansuda: Solved in v6.0.1.0:
- https://github.com/kimmknight/remoteapptool/issues/83

cc @kimmknight.
