### ISSUE TITLE
no app toolbar icon on ubuntu

### ISSUE THREAD

**Issue by zzgundam** [kimmknight/remoteapptool#21]
i ran remoteapp on windows client with app's toolbar icon successfully.but on ubuntu system, it started a fix-sized rdp window, and when running multiple apps in a session, not app's icon showed in toolbar.
what can i do to make it the same as windows client in ubuntu client?

**Comment by MrBrianGale** [comment]
Pretty sure this "bug" is with the client you are using.  What RDP client are you using in Ubuntu?'
I just tested this on my Ubuntu install with xfreerdp and I get an app icon in the toolbar as expected.

My guess is it is something you have misconfigured in the app you are using for opening the RDP connection.

**Comment by kimmknight** [comment]
This issue appears to be with the RDP client you are using on Ubuntu, not with RemoteApp Tool. Here probably isn't the best place to find your answer.

You could try asking on the [RemoteApp Tool forum](https://groups.google.com/forum/#!forum/remoteapptool), or better yet, see if you can find a forum for the RDP client you are using.

Best of luck to you @zzgundam !
