### ISSUE TITLE
Keyboard Language Bar

### ISSUE THREAD

**Issue by VineReis** [kimmknight/remoteapptool#22]
When you connect via RemoteApp, with the connection starting to be made, a keyboard bar goes up and out, it doesn't even appear in the Task Manager.
![bug](https://user-images.githubusercontent.com/67743689/86360685-16d65080-bc49-11ea-8f06-7b4f8caa3dda.jpg)

**Comment by MrBrianGale** [comment]
That keyboard language bar is coming from the remote server, not the local machine.  You can verify this by changing it to another language and starting up a non-remote app (notepad for example) and you will see the letters are in your local system language.

To make that not pop up, you either need to disable it the first time it comes up or configure it on your server to not start.

Does that address your concern?

**Comment by goodhyun** [comment]
Even if the IME is safely stuck in the Taskbar of the remote server, it keeps popping up whenever we connect to any apps. 
Moreover, it wouldn't minimize by clicking the minimize button on the Language bar if it's on the remote screen.

**Comment by MrBrianGale** [comment]
True.  But this is unrelated to the RemoteApp Tool here, it is how your specific windows server is configured to do things.
You would get the same thing if you used the Windows Server RemoteApp features that are built in.

I expect there is a GPO you can set to get rid of that or if it is not a domain joined computer, there are settings on the SERVER you can set to get rid of that.

Unfortunately, there is nothing that can be done from the RemoteApp Tool to disable that.
