### ISSUE TITLE
Optimize for Retina displays? 

### ISSUE THREAD

**Issue by goodhyun** [kimmknight/remoteapptool#23]
<img width="459" alt="Screen Shot 2020-07-04 at 10 08 24 AM" src="https://user-images.githubusercontent.com/4727708/86502460-6306c980-bdde-11ea-96b6-92fd9df24229.png">

looks like Retina support is missing ?

**Comment by MrBrianGale** [comment]
Unfortunately, that option is designed specifically for the tool you are using.  It is not a standard RDP feature that I can see.
The list of supported RDP features are available here:
https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/rdp-files

A quick google, that feature is something added to Remote Desktop for MAC.

That being said, we MAY be able to add it in still.
Could I get you to mark that checkbox off, click on "Save", then copy-paste the text of an rdp file (open it in notepad or equivalent) into this issue?  I need to see what the RDP file looks like when that is checked off to know what needs to be added or changed.

**Comment by goodhyun** [comment]
Thanks, but that specific setting is not making any differences in the .rdp files. 
This app is just a genuine Microsoft RDP for macOS, and that feature seems to be related to the DPI remoting or so.  

https://superuser.com/questions/830234/remote-desktop-into-windows-8-1-pc-with-high-dpi-scaling 
This is exactly what I got with the above settings. 

Everything pixels got 2x, not utilizing the retina screen at all. The question now, if supposing the answer above can be applied here, is how can we start a new session on the server side. ?

**Comment by MrBrianGale** [comment]
To start a new session on the server side, you need to terminate the existing session.  Alternately, you can reboot the server, but you don't want to do that every time you need to reset your session.
Your server administrator should be able to do this.  There are also GPO settings you can apply to the server to have the session terminated when the session disconnects.  By default this is not the case and I believe the default is to keep the session open indefinitely.
The reason this is the default is that next time you start the connection, your session is already running on the server and less processes need to start which improves performance.

As this feature (optimize for Retina displays) is not being implemented, I am going to close this issue.
