### ISSUE TITLE
Unable to start edge.

### ISSUE THREAD

**Issue by sbeaudoin** [kimmknight/remoteapptool#26]
Successfully created and able to use two RDP shortcut.  Used the same tactic for a shortcut to edge, same host, same client.  When I use it on the client, it ask me to authenticate, show no error and I can see the language toolbar, but there is no window.  Used the same tactic for chrome and it works.  

I used the edge **Windows** shortcut to find the executable location and the command line options.  It is ""C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --profile-directory=Default".  I tried without the command line options with no success.  In details I tried :

- Path : C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
- Command line : --profile-directory=Default

And then :

- Path : C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
- Command line : "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --profile-directory=Default

And then :

- Path : C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
- Command line : Empty

A help file, describing the fields of the app would be useful on the wiki.   I need details about the format of the "command line" field.  Must if be only the options or the complete command line?  What is VPath?  What are the role of the different "Command line options" choices?  So many questions and no easy way to find them.

**Comment by sbeaudoin** [comment]
Forget this, closed all "full" RDP sessions to host and all remote app sessions and it now works.  It is configured as indicated in the third option abose.

**Comment by Rakly3** [comment]
I can't get it to work either. Other browsers, ie Chrome, work fine.
Any ideas?

**Comment by kimmknight** [comment]
@sbeaudoin thanks for the suggestion - I've [added a page to the Wiki](https://github.com/kimmknight/remoteapptool/wiki/RemoteApp-Properties-explanation) explaining the RemoteApp properties.
