### ISSUE TITLE
After windows update ( W10 2004 ) on the host the RDP file generated by remote app no longer works

### ISSUE THREAD

**Issue by bradphelan** [kimmknight/remoteapptool#32]
When using the RDP file generated by remote app I get the error 

![image](https://user-images.githubusercontent.com/17650/90501742-14727c00-e14d-11ea-8d2c-9474f2ddaa5d.png)

However RDP still works if I use the plain remote desktop method. Also if the credentials are saved then using plain old remote desktop no longer works. I have to clear credentials and log in again. If I use the remote APP RDP file again with saved credentials then I will be locked out again with the above error.

On the host machine I tried recreating the RDP file from zero. This doesn't seem to make a difference.

**Comment by MrBrianGale** [comment]
What version of the RemoteApp Tool are you using?
Are you using Windows 10 home or pro?
What version of windows is the RDP file connecting to (server, home, pro, etc)?
Does the RemoteApp RDP work if you DON'T save the credentials?

**Comment by bradphelan** [comment]
![image](https://user-images.githubusercontent.com/17650/90870704-41679e80-e39a-11ea-96b9-d5171d61e97c.png)

The remote machine
![image](https://user-images.githubusercontent.com/17650/90870770-5ba17c80-e39a-11ea-83e6-6a3042480c38.png)

The local machine
![image](https://user-images.githubusercontent.com/17650/90870850-7aa00e80-e39a-11ea-9e7d-fd41538c4ea5.png)


It does not work if I do not save the credentials. However if I save the credentials RDP fails to work even if I'm not using the remoteapp generated RDP file.

**Comment by kimmknight** [comment]
Thanks @bradphelan. I agree @MrBrianGale, this seems to be an issue with Window RDP/RemoteApp, not with RemoteApp Tool.

Removing the saved credential using Credential Manager might resolve this. Find the Windows Credential that matches the remoteapp host (it will start with TERMSRV/ ) and remove it.

![image](https://user-images.githubusercontent.com/45035595/92999120-d2790200-f561-11ea-8c2c-37a40ac31a08.png)
