### ISSUE TITLE
RDWebService.asmx not found

### ISSUE THREAD

**Issue by seflerZ** [kimmknight/remoteapptool#49]
Hello everyone. I'm using remoteapp tools to host my remote app on win10 pro. Everything works great, but the tray icon seems to be disconnected. When click "reconnect" it tells the "RDWebService.asmx not found error"

**Comment by sashaqwert** [comment]
This is not an Issure to the RemoteApp Tool. (If using RAWeb)

If using RAWeb, please post this Issure there.

**Comment by seflerZ** [comment]
okay, close this.
