### ISSUE TITLE
Add command-line support

### ISSUE THREAD

**Issue by kimmknight** [kimmknight/remoteapptool#5]
Add, remove and modify RemoteApps. Create client connections.

**Comment by bmg002** [comment]
Is this needed?  I think if end users want command line remote apps, there are powershell tools that will do it for them.  I feel like adding it to this tool would be reinventing the wheel, no?

**Comment by kimmknight** [comment]
Ahh good point. This has been on the todo list since before I discovered the Powershell RemoteApp commands. Creating MSIs is the only useful feature that can't be done in Powershell, and as we already have command-line support for that (RDP2MSI), I agree, we can close this issue.
