### ISSUE TITLE
RemoteApp doesn't display second opened program

### ISSUE THREAD

**Issue by libots** [kimmknight/remoteapptool#59]
I'm using the tool to display VSCode remotely. I'm signing my commits, which brings up a password prompt (using pinentry-qt.exe from GnuPG). Unfortunately, said prompt is not displaying on my remote terminal. If I bring up a regular RDP session to the desktop, it shows there, but that's rather inconvenient as it requires me to close the remote app connection, open the desktop, and then switch back. Is there any workaround for this?

**Comment by libots** [comment]
Fixed this by checking the "Allow Unlisted Remote Programs" box in "Host Options" and then rebooting. :-)

**Comment by kimmknight** [comment]
Nice one! Thanks for sharing!
