### ISSUE TITLE
VPath not being filled when creating apps

### ISSUE THREAD

**Issue by kimmknight** [kimmknight/remoteapptool#6]
Should we even keep VPath??

**Comment by bmg002** [comment]
Doing a quick look through the code, VPath is being written to the registry when it creates the remoteapp.  Doing some quick (although painful) googling found a powershell command New-RDRemoteApp that creates new remote desktop remote apps.  According to that command:
The parameter FileVirtualPath needs to resolves to the same location as the value of the FilePath parameter, while FilePath must be a valid local path on all Remote Desktop Session Host (RD Session Host) servers in the collection.

FileVirtualPath seems to be the VPath value so I think it needs to be kept it in there, but may not need to presented to the end user?

**Comment by kimmknight** [comment]
I remember someone saying that the VPath can take system variables, whereas the regular Path cannot. That made me think it was useful to present the option to the user, but perhaps we could take it out and see if anyone complains. What do you think?

**Comment by bmg002** [comment]
From what I was reading, that is correct.  VPath can take system variables (such as %TEMP% or %SYSTEMDRIVE%), but it needs to point to the same physical file location as the regular file path.  The exception is if you are using a "Windows Virtual Desktop" in which case you provide either the FilePath OR the FileVirtualPath, not both.  With a RemoteApp it sounds like you NEED to provide the FilePath and the FileVirtualPath is optional.
My sources:
https://docs.microsoft.com/en-us/powershell/module/remotedesktop/new-rdremoteapp
https://docs.microsoft.com/en-us/powershell/module/windowsvirtualdesktop/New-RdsRemoteApp

So thinking it is probably safe to ignore the VPath field and possibly clone it to the Path when writing to the registry?  Not 100% certain and would likely need some testing, but should work.

**Comment by kimmknight** [comment]
Good to know, thanks! I agree, the **vpath** setting should be hidden from the user and just be cloned from the **path** setting (in the rdp file).

That will help give the Properties window a well-needed tidy-up!

**Comment by kimmknight** [comment]
Removed VPath and redesigned the Edit window. Need to do more testing before merging
