### ISSUE TITLE
Running on XP pro SP3 RstrtMgr.dll error

### ISSUE THREAD

**Issue by affa247** [kimmknight/remoteapptool#60]
runs fine on xp pro sp3 when adding app. Registry updated fine.
When selecting save rdp file a new pop up menu comes up for option selections, which is normal.
But hitting the save button will result in RstrtMgr.dll not found error. I can choose to continue and ignore the error but the app will just go back to the main screen.

**Comment by zbalkan** [comment]
RstrtMgr.dll is a newer component than Windows XP. AFAIK, it started with Windows 7 but it might be Vista. That needs some clarification. Therefore, it's not possible to solve this issue in the scope of remoteapptool.

**Comment by kimmknight** [comment]
Interesting. XP users may need to use the previous version of the tool for the moment

**Comment by MrBrianGale** [comment]
Something to note- XP (and vista and 7) is out of support by microsoft; both standard and extended support. Anyone still using XP is taking a risk and shouldn't have those computers exposed to the internet...

**Comment by spz2020** [comment]
> Interesting. XP users may need to use the previous version of the tool for the moment

Which version?

**Comment by kimmknight** [comment]
@spz2020 you can grab the old versions from:

https://github.com/kimmknight/remoteapptool/wiki/Version-history-(pre-GitHub)

I reckon 5.3.0.0 should work but if it doesn't, try an earlier one!
