### ISSUE TITLE
Dialog to save user credentials on next login is ignored

### ISSUE THREAD

**Issue by bradjtrammell** [kimmknight/remoteapptool#61]
When a user connects to a system they get the security dialog about remembering the password and ignoring the certificate on the next login. 

The input on these dialog boxes seem to be ignored as they pop up every time the icon is clicked. Even if it is done multiple times per session.

**Comment by kimmknight** [comment]
Yep, totally annoying. I believe this is related to the RDP client and the host - not remoteapp tool
