### ISSUE TITLE
Add support for IPv6

### ISSUE THREAD

**Issue by connected201** [kimmknight/remoteapptool#65]
hi, created remoteapp, using ipv6, but remoteapp tool, delete duble dots from ipv6 address when i save .rdp file 
Results:
![image](https://user-images.githubusercontent.com/20506433/144883291-52b03b36-bb36-4bbb-bbd2-82b9ba9d3c58.png)

**Comment by kimmknight** [comment]
Good idea! I think this should be relatively quick to implement
