### ISSUE TITLE
problem with windows 7

### ISSUE THREAD

**Issue by bouhlal** [kimmknight/remoteapptool#67]
Hello
I have installed it on windows 7 32bit, when I try to login via rdp (after I type login and password) the session closed without any error msg. on windows 10 32bit and 64bit works without error

**Comment by kimmknight** [comment]
As stated in the README:

**If you try to host RemoteApps on an incompatible edition of Windows (eg. Windows 10 Home), the tool will run but RemoteApps will not work. The RDP client will appear to be connecting, then just disappear with no error shown.**

A supported edition of Windows XP, 7, 8, 10, or Server is required. See the [compatibility chart](https://github.com/kimmknight/remoteapptool/wiki/Windows-Compatibility).

**Comment by bouhlal** [comment]
Thank you so much i tried it on windows 7 pro i will misgrate to enterprise
