### ISSUE TITLE
rdpwrap question

### ISSUE THREAD

**Issue by test2a** [kimmknight/remoteapptool#68]
does this require rdpwrap or can remote users connect without rdpwrap? i have had problems with failing rdpwrap every few months and i would've liked if something could avoid it. 

i do not see any documentation or issues regarding this so anyone ?

**Comment by MrBrianGale** [comment]
It depends on what you are trying to do.
If you want remote apps to be available to an end user, this tool does that.
If you want to circumvent restrictions put in place on a Windows OS to allow a single-user version of the OS (Windows 10 for example) to allow multiple users to be able to log in to the computer and run the same app at the same time, this won't help with that.

If you are looking for a "good" way to get around needing rdpwrap for remote apps on a single-user OS host, I recommend buying a license for Windows Server and some user CAL's for that to allow multiple users to use the server at once.
