### ISSUE TITLE
It's possible to use your code in commercial purposes?

### ISSUE THREAD

**Issue by connected201** [kimmknight/remoteapptool#69]
It's possible to use your code in commercial purposes? if yes, it's possible to negotiate about your revenue? (i want to integrate https://github.com/kimmknight/rdpx and https://github.com/kimmknight/raweb) in my product.
Also i will need support of your software.

**Comment by kimmknight** [comment]
Hi connected201, rdpx and RAWeb are licenced under the MIT licence which allows you to do what you are suggesting. Royalties or even just crediting are much appreciated, but not required :-)

I'm interested to hear about your idea.
