### ISSUE TITLE
hide the connection window

### ISSUE THREAD

**Issue by xrahitel** [kimmknight/remoteapptool#70]
how to hide this window from the user https://i.postimg.cc/v84zJS0Q/2022-03-15-142002.gif

**Comment by kimmknight** [comment]
The Remote Desktop Client (mstsc) does not appear to have any options for hiding that window.

Also, setting the program to start minimized _will_ hide the window from the user, it will also hide the RemoteApp once it has started.

![image](https://user-images.githubusercontent.com/45035595/158518766-2baf9db1-b21c-4f18-8145-1dcdd0ce9c46.png)

For future reference, here is the list of **mstsc.exe** command-line options:

![image](https://user-images.githubusercontent.com/45035595/158518009-01296740-757c-4c22-91cc-d43b20dfb82c.png)

**Comment by seflerZ** [comment]
Once the connection was established, the window will not appear when starting other remote apps.
