### ISSUE TITLE
Missing task icon on windows11

### ISSUE THREAD

**Issue by xiaoyao9184** [kimmknight/remoteapptool#71]
When connecting to the RemoteAppTool host using Windows 11 client, the icon on the taskbar missing, this will not work for remote apps that are minimized restore or reminders. 

I'm sure it's a windows issue, after searching i can't find a solution, is it too niche to use remote app?

**Comment by kimmknight** [comment]
I think this is unexpected behaviour. It seems to be an issue with your app or with Microsoft Remote Desktop/RemoteApps, not RemoteApp Tool. Do post back here if you found/find a solution though!
