### ISSUE TITLE
Display at strange scale

### ISSUE THREAD

**Issue by HoranZuo** [kimmknight/remoteapptool#72]
I use Macbook Pro 14 to Connect Navicat Premium, but it display at strange scale
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/35492958/162454897-a6b9af93-ad9f-41f2-b842-e4e9fcfd86e1.png">

I try to adjust Microsoft Remote Desktop App's options but does not work 
<img width="380" alt="image" src="https://user-images.githubusercontent.com/35492958/162454830-efc1fd90-0fd7-48dc-bd45-d738a52d93be.png">

my MBP's resolution is 3024 x 1964 macOS Monterey 12.3.1
my remote desktop resolution is 1920 x 1080, Operation System version is Windows Server 2019

**Comment by Strange-Panda** [comment]
The problem lies in "Fit session to window". 
Disable the option and adjust the resolution of the client. 
This is not a bug but a configuration error.

**Comment by kimmknight** [comment]
No reply so I'll assume this fix works
