### ISSUE TITLE
BUG in file association ico path generation

### ISSUE THREAD

**Issue by seflerZ** [kimmknight/remoteapptool#73]
The current "webfeed.aspx" generate associated file ico path like:
![image](https://user-images.githubusercontent.com/2093588/173053382-c6ca5e34-30da-4521-92a2-c0fb885a9a76.png)

Which adds two dots before extension name. The reason is simple, the code add extra dot in line 89:

```
string docicon = basefilename + "." + filetype + ".ico";
```

**Comment by kimmknight** [comment]
Thanks for this 👍 I have posted it in the RAWeb repository and will close it here.
