### ISSUE TITLE
Local Authority Authentication and Adding users

### ISSUE THREAD

**Issue by DanteLogan** [kimmknight/remoteapptool#74]
Having a problem entering user credentials when trying to open a remote app. Host client has all the necessary remote desktop settings on and enabled as well as the client. Also to clear way of how to create user credentials for new user to connect to. When credentials are entered e.g using host credentials to sign in on the client prompt screen error is popping up
![Capture](https://user-images.githubusercontent.com/97335578/182089687-b6bb5967-d848-4609-ba66-500bf55feb3c.PNG)

**Comment by MrBrianGale** [comment]
The credentials are the same you use for RDP. Permissions to remote app are not managed by this tool and as such, this issue is not with the tool and I'm going to close this issue.
Basically, if you can RDP to the server, you can remote app to it. If you can't, you need to fix that first.
