### ISSUE TITLE
Crash when add any program

### ISSUE THREAD

**Issue by zhaodice** [kimmknight/remoteapptool#76]
![Screenshot_20220821_142424](https://user-images.githubusercontent.com/63996691/185778477-5933847b-af57-4eeb-b5ee-c7e7a42ae319.png)

System: Windows 7

**Comment by MrBrianGale** [comment]
Is there any more error information? The bit that is in this issue isn't enough to go on. Will need the stack trace information and steps to reproduce the error before any work can be done

**Comment by MrBrianGale** [comment]
How about the steps to reproduce the problem in as much detail as possible?
Also, are you using a compatible version of windows (https://github.com/kimmknight/remoteapptool/wiki/Windows-Compatibility)?

**Comment by kimmknight** [comment]
No updates. Closing for now. Reopen if pain persists.

**Comment by mikaelxu** [comment]
I had exactly the same issue. I copy the crash error message below for your reference. am also attaching some screenshots. 

My Win7 Enterprise (x64) is installed as Proxmox VM. The crash happens on this Win7 x64.
However, when I changed the installation to Win7 Enterprise (x86), RemoteApp Tool worked and did not crash when adding the app.

<img width="1038" alt="Screen Shot 2024-02-16 at 11 28 39" src="https://github.com/kimmknight/remoteapptool/assets/6264853/041050a6-1bef-4527-a54f-e4482f5b2ea3">

<img width="792" alt="Screen Shot 2024-02-16 at 11 29 09" src="https://github.com/kimmknight/remoteapptool/assets/6264853/2c082e57-e023-4039-a942-fe55c17530cf">

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	RemoteApp Tool.exe
  Application Version:	6.0.0.0
  Application Timestamp:	600ab067
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.1.7601.17514
  Fault Module Timestamp:	4ce7c8f9
  Exception Code:	c00000fd
  Exception Offset:	0000000000057d6b
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	18441
  Additional Information 1:	e9f9
  Additional Information 2:	e9f9ed03e73cb6be7af6e409c71651d1
  Additional Information 3:	c37c
  Additional Information 4:	c37c302195599ac1ab6bb9a17adc799f

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by amazingfate** [comment]
> Same issue adding `c:\cmd.exe` on windows server 2012r2.

After installing all windows updates, this issue is gone.

**Comment by Ansen** [comment]
> I wonder if it's something to do with Unicode characters. @Ansen does the path to the EXE you are trying to add contain any non-ASCII characters?
> 
> Could you try putting the EXE in the root of one of your drives and adding it as a RemoteApp?

It's still error with "c:\7\7zFM.exe"



![image](https://github.com/kimmknight/remoteapptool/assets/676412/17db13ad-1a2c-49e0-8f45-1d5b3444e860)

![image](https://github.com/kimmknight/remoteapptool/assets/676412/51a86c1a-8361-4856-9d80-624e6f8aa5be)


**And 2022R2 works well**

**Comment by kimmknight** [comment]
Thanks for testing that.

🤔
