### ISSUE TITLE
RemoteApp Tool v 6.0.0.0 fails on Windows 7 Ultimate VM -but- RemoteApp Tool v 5.3.0.0 works.

### ISSUE THREAD

**Issue by bmullan** [kimmknight/remoteapptool#78]
just an FYI...

> Ubuntu 22.04 Host
> - xfreerdp2

> Virtual-Box
> - Windows 7 Ultimate VM
> - .NET v4

Innstallation of [RemoteApp Tool 6.0.0.0 Installer](https://github.com/kimmknight/remoteapptool/releases/download/v6.0.0.0/RemoteApp.Tool.6000.msi) - Fails!

However, installation of [RemoteApp Tool 5.3.0.0 Installer](http://www.kimknight.net/remoteapptool/RemoteApp%20Tool%205300.msi) works on the Windows 7 Ultimate VM

And using xfreerdp from the Ubuntu 22.04 Host I can successfully run remoteapp's from the Windows 7 VM in a
window on my Ubuntu Desktop.

**Comment by kimmknight** [comment]
Good to know, thanks. This is due to using a newer version of the MSI Packager (Advanced Installer) which builds MSI installers that are incompatible with earlier Windows versions.

The download is also available as a ZIP file which should work on this platform.
