### ISSUE TITLE
How to set startup parameters

### ISSUE THREAD

**Issue by zhangheng0027** [kimmknight/remoteapptool#81]
How to set startup parameters

For example:

"C:\Program Files\Oracle\VirtualBox\VirtualBoxVM.exe" --startvm win7

Now share the cmd and enter the above command

**Comment by kimmknight** [comment]
On the RemoteApp, set:

App path: C:\Program Files\Oracle\VirtualBox\VirtualBoxVM.exe
Command line option: Enforced
Command line parameters: --startvm win7
