### ISSUE TITLE
Disabled printer redirect

### ISSUE THREAD

**Issue by bolfenk** [kimmknight/remoteapptool#83]
Hi,

where can disabled printer redirect with remoteapp tool. I have problem when user run remoteapp-rdp client, newtork printer stop working. 

Tnx

**Comment by Neustradamus** [comment]
@kimmknight: It is possible to add a ticket for this feature?

Thanks in advance.

**Comment by kimmknight** [comment]
> @kimmknight: It is possible to add a ticket for this feature?
> 
> Thanks in advance.

Hi @Neustradamus. Good timing in your request. The ability to change RDP file parameters was added to the release v6.0.1.0 a week or two ago.

You can now edit most RDP options.

Grab the latest version.

Click the "RDP options..." button in the Options tab when creating a client connection. Modify any options required (in your case "redirectprinters"). You can save this for all future connections by clicking "Save settings" on the previous screen.

**Comment by Neustradamus** [comment]
@kimmknight: Nice, good job!
