### ISSUE TITLE
MacOS Unable to add workspace

### ISSUE THREAD

**Issue by SgtBill88** [kimmknight/remoteapptool#85]
Hi there, I’m able to add the workspace via webfeed to all windows devices but anything mobile or MacOS having no luck. Is this an issue or user error. Thanks for the outstanding project. Love it!!

**Comment by MrBrianGale** [comment]
As a guess, I would say it is a limitation of the RDP client you are using. I do not have a MacOS computer to test this on, but found this link:
https://community.spiceworks.com/topic/2209111-remoteapp-on-a-mac
Not the most recent article, but do those steps work?

As for mobile, I think you have the same snags - it depends on the app you use.

**Comment by kimmknight** [comment]
Glad you like the tools!

I assume you are referring to [RAWeb](https://github.com/kimmknight/raweb)? If so, yep, I believe the official Mac RDP client hasn't been compatible with RAWeb for ages. Android is possible using version 8 of the RDP client. See [this issue](https://github.com/kimmknight/remoteapptool/issues/91) for info on how to get it.
