### ISSUE TITLE
This tool can publish application in RDWeb？

### ISSUE THREAD

**Issue by weili0677** [kimmknight/remoteapptool#86]
This tool can publish application in RDWeb？
such as tool publish application then login RDWeb can see this application.
I wan't to make the server to AD server.

**Comment by kimmknight** [comment]
Yes, you use RemoteApp Tool to create an RDP file and save it in the **\rdp** folder of RAWeb.

**Comment by weili0677** [comment]
> Yes, you use RemoteApp Tool to create an RDP file and save it in the **\rdp** folder of RAWeb.

Thank you.but I put the RDP file in the RDWeb\rdp folder or RDWeb\pages\rdp folder also can't see the application and why?
