### ISSUE TITLE
Not work in windows 8.1 pro

### ISSUE THREAD

**Issue by janiiith** [kimmknight/remoteapptool#87]

**Comment by MrBrianGale** [comment]
That is correct. It is documented in the company list.

**Comment by janiiith** [comment]
is there any special reason for that?any solution?

**Comment by MrBrianGale** [comment]
Yes - windows 8.1 pro doesn't support remote apps. Solution is to use a different version of windows. Windows 8.1 is no longer supported by Microsoft. I recommend upgrading to a supported version.

**Comment by janiiith** [comment]
Thanks for the tip!
