### ISSUE TITLE
How to select a windows apps into list

### ISSUE THREAD

**Issue by cadem** [kimmknight/remoteapptool#89]
I want to select a windows apps into list when clicking plus button, but I can't find out the windows apps like explorer, or windows terminal, I got the windows terminal through the microsoft app store. How do I select a windows apps?

**Comment by kimmknight** [comment]
You can locate Windows Explorer at c:\windows\explorer.exe

However I am not aware of a way to add Windows Apps (from the app store) as RemoteApps.

Would love to hear if anyone knows a way!

**Comment by MrBrianGale** [comment]
I mean, if you grab the exe, then any exe will work. the app store ones are
just hard to find. You need to know where to look and what to look for.
SOME are installed in the user profile, so they are not shared across
users, and SOME are installed for all users access, but the parent folder
is not.
C:\program files\windowsapps is one location and the other is in the user
profile, but I forget where exactly... in appdata\local somewhere, but I
don't remember the exact path offhand, but it is a protected folder (access
only given to the user who owns the parent folder and admins)

**Comment by jks-liu** [comment]
My workaround is to create a `*.cmd` file to open Windows Apps, then add this cmd file to the list.

So, this question becomes how to open Windows Apps in cmd. For some apps it is easy, for e.g., you can use below command to open Windows Store:
```cmd
start ms-windows-store:
```

But for other Windows Apps, we need another way. For e.g., I'd like to open Microsoft Todos, I can use below command (in my PC, maybe different in yours):
```cmd
start shell:AppsFolder\Microsoft.Todos_8wekyb3d8bbwe!App
```
The key is to find the app's full name of `Microsoft.Todos_8wekyb3d8bbwe`.

We can use below command to search the app's full name (Below command should be run in PowerShell):
```ps1
Get-AppxPackage | Select-Object Name, PackageFullName | Where-Object { $_.Name -like "*todo*" }

Name            PackageFullName
----            ---------------
Microsoft.Todos Microsoft.Todos_2.104.62421.0_x64__8wekyb3d8bbwe
```
Then change the search result to above pattern, delete the version string and do not forget the `!App` in the end.

**Comment by kimmknight** [comment]
Great idea @jks-liu 👏👏👏

I have added your post to the Wiki. I'll close this issue but create an issue to add a feature that allows selection of Windows store apps.

**Comment by wukan1986** [comment]
> 

great idea!

I can only create one rdp file, and start a lot of apps in one session.
