### ISSUE TITLE
RD Client for Android

### ISSUE THREAD

**Issue by liweishu** [kimmknight/remoteapptool#91]
It can‘t be published as a url, and the program can’t be run on RD Client for Android.

**Comment by kimmknight** [comment]
If you are talking about [RAWeb](https://github.com/kimmknight/raweb), unfortunately it doesn't work with the latest Android RD client. It does however work with the old Android RD client app ([Microsoft Remote Desktop 8](https://play.google.com/store/apps/details?id=com.microsoft.rdc.android)).

If you can't get it from the Play Store, you might be able to find an APK and install that. The version I have installed on my devices is: Microsoft Remote Desktop 8.1.81.435.

**Comment by justinozavala** [comment]
Is there any android client able to work with remoteapptool?

**Comment by kimmknight** [comment]
> If you are talking about [RAWeb](https://github.com/kimmknight/raweb), unfortunately it doesn't work with the latest Android RD client.

For anyone still looking at this, the latest version of RAWeb now supports new Android RD Clients.

Windows auth must be enabled on the *auth* folder in IIS. If you download RAWeb, extract it, and run *setup.ps1* in PowerShell (running as administrator), it will set everything up for you.

**Comment by justinozavala** [comment]
Thank you. I deleted my comment because I realized this was explained above.
