### ISSUE TITLE
msi doesn't work after wix is installed.

### ISSUE THREAD

**Issue by cadem** [kimmknight/remoteapptool#92]
I install wix, and I can run wix --version correctly. But I still can't select msi option. What else do I need for msi?

**Comment by MrBrianGale** [comment]
To confirm, did you reboot after installing Wix?

**Comment by zc640618** [comment]
Try to use WIX3 instead of WIX4.
https://github.com/wixtoolset/wix3/releases

**Comment by kimmknight** [comment]
I've updated the WiX link on the README to point to WiX v3.

I'll create a new issue to add support for WiX v4 then close this issue.
