### ISSUE TITLE
Can't move Windows between different Displays

### ISSUE THREAD

**Issue by CptBademantel** [kimmknight/remoteapptool#93]
If you open a Browser on one Window and then start Dragging it to a different Display, it resets the Position when the Cursor hits the Border.

If you move the Window over without having the Cursor touch the Border, then move the Cursor over without dragging you can drag it over on the other Display.

**Comment by CptBademantel** [comment]
After some weir unplugging and replugging i've actually think i found the Problem(s)
1. All Displays should have the same Resolution
2. Primary Display should be (Top) Left
3. The Primary Display should be connected to Windows Preferred Port ( with my Systems it was Hdmi>VGA)
4. The Max resolution may not be higher than 4096x2048

When i used these 4 Conditions it works flawlessly, if one of them is not fullfilled it doesnt work most of the times.

**Comment by MrBrianGale** [comment]
Not re-opening this issue, but wanted to add that this would be a limitation of the RDP client, not the remote app tool. Different client tools will have different requirements and what MAY work for CptBademantel may not work for everyone. I recommend reviewing the documentation in your RDP client and/or contacting the RDP client for support.
